version: "3.7"

services:

  backend:
    build: back
    image: piclodio-back
    volumes:
      - /tmp/static:/code/static
      - ${PWD}/piclodio_db:/code/db
    devices:
      - /dev/snd:/dev/snd # audio control
    ports:
      - "8000:8000"

  frontend:
    build: front
    image: piclodio-front
    ports:
      - "80:80"
    volumes:
      - /tmp/static:/static
    depends_on:
      - backend
